### ISSUE TITLE
log10() 函数的精度不足

### ISSUE THREAD

**Issue by 1YOUYUNLIN1** [WhiteCatBlackHat/whitecatblackhat.github.io#1]
![image](https://github.com/user-attachments/assets/684a75bb-8c38-4931-a17b-191615b77e70)
log10(100.00) 的计算结果应为 2.0000 而不是 2.0043

**Comment by WhiteCatBlackHat** [comment]
将会处理，感谢贡献。

**Comment by WhiteCatBlackHat** [comment]
![没有发现bug](https://github.com/user-attachments/assets/1f69bc15-f468-4e13-9f8b-0472da3f2e86)

请提供进一步资料

**Comment by 1YOUYUNLIN1** [comment]
![image](https://github.com/user-attachments/assets/2c96fd5b-a383-4d68-a687-df352c3fb21e)
似乎是因为加了 1 ?

**Comment by WhiteCatBlackHat** [comment]
相关部门（指只有一个人的开发组）已介入调查。

**Comment by WhiteCatBlackHat** [comment]
![1e821和1e822](https://github.com/user-attachments/assets/46d1bb7e-5905-495b-8297-0aa9dbb5e563)

实验表明，1e822比1e821能多得一个无限点数，所以log10的结果不同。

**Comment by WhiteCatBlackHat** [comment]
这应该不算是一个bug，因为1e821和1e822本身能得的无限点数就不同。

**Comment by 1YOUYUNLIN1** [comment]
但是100.00无限点数确实会导致2.0043

**Comment by WhiteCatBlackHat** [comment]
请提供进一步资料……

**Comment by WhiteCatBlackHat** [comment]
![QQ_1721220877270](https://github.com/user-attachments/assets/9d25f244-b934-4f76-98cf-928af8e7677a)

应该是这样的，所谓的'100.00'可能是100.001被四舍五入的结果。

但是无限点数确实不应该出现小数部分，所以请提供进一步资料。

```javascript
var x = new bigNum(1.00001,2)
log10(x)
expToStr(x)
```

**Comment by 1YOUYUNLIN1** [comment]
是否因为`log10(0)`会导致错误，所以此处使用的是`log(infPoints+1)`？

**Comment by WhiteCatBlackHat** [comment]
请问“此处”指的是？

请提供源码中的片段。

**Comment by 1YOUYUNLIN1** [comment]
在 factor.js 中的 IGFac() 中使用了 +1 。
问题解决了。

**Comment by WhiteCatBlackHat** [comment]
![这里吗](https://github.com/user-attachments/assets/02da89a3-7746-48db-bd60-a14152ce5469)

你是说这里吗？

这里是因为无限次数

**Comment by WhiteCatBlackHat** [comment]
此issue到此结束。
